[tasks.lli]
dependencies = ["build"]
script = "lli --lib $(rustc --print sysroot)/lib/libstd*.so target/debug/${@}"

[tasks.end]
# Runs after any make tasks, lets use it to stitch together all the .bc files to whatever we built
